# Generated by Django 4.2.10 on 2026-03-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='tag',
            field=models.CharField(blank=True, help_text='Admin tag like Support, Quote Inquiry', max_length=50, null=True),
        ),
    ]
