# Generated by Django 4.2.10 on 2026-06-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_chatthread_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin_message',
            field=models.BooleanField(default=False),
        ),
    ]
