# Generated by Django 5.2.8 on 2026-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='already_sent',
            field=models.BooleanField(default=True),
        ),
    ]
