# Generated by Django 4.2.10 on 2026-04-15 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_external_client_alter_job_booking_and_more'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection', to='jobs.job'),
        ),
    ]
