# Generated by Django 5.2.8 on 2026-01-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connectionrequest_already_sent'),
        ('services', '0008_alter_clientservicepreference_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection', to='services.serviceschedule'),
        ),
    ]
