# Generated by Django 4.2.10 on 2026-02-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landscaperprofilies',
            name='plan',
        ),
    ]
