# Generated by Django 4.2.10 on 2026-02-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_landscaperprofilies_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscaperprofilies',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
