# Generated by Django 5.2.8 on 2026-01-03 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0002_landscaperprofile_profile'),
        ('profiles', '0003_alter_workerprofile_pro_landscaper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workers/'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='pro_landscaper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='landscapers.landscaperprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
