# Generated by Django 4.2.10 on 2026-02-05 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_landscaperprofilies_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscaperprofilies',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landscaperprofilies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LandscaperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landscaper_profile_extra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
