# Generated by Django 5.2.8 on 2026-01-03 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0002_landscaperprofile_profile'),
        ('profiles', '0004_alter_workerprofile_image_alter_workerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='pro_landscaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscapers.landscaperprofile'),
        ),
    ]
