# Generated by Django 4.2.10 on 2026-02-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('profiles', '0004_alter_landscaperprofilies_user_landscaperprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscaperprofilies',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan'),
        ),
    ]
