# Generated by Django 5.2.8 on 2026-01-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        ('profiles', '0005_alter_workerprofile_pro_landscaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='pro_landscaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitations.teaminvitation'),
        ),
    ]
