# Generated by Django 4.2.10 on 2026-02-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_landscaperprofilies_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='calendar_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='service_reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landscaperprofilies',
            name='calendar_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landscaperprofilies',
            name='service_reminder_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
