# Generated by Django 5.2.8 on 2026-01-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_workerprofile_pro_landscaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='name',
            field=models.CharField(default='Worker', max_length=255),
        ),
    ]
