# Generated by Django 4.2.10 on 2026-02-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_clientprofile_calendar_sync_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientprofile',
            old_name='calendar_sync_enabled',
            new_name='calendar_sync',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='service_reminder_enabled',
            new_name='service_reminder',
        ),
        migrations.RenameField(
            model_name='landscaperprofilies',
            old_name='calendar_sync_enabled',
            new_name='calendar_sync',
        ),
        migrations.RenameField(
            model_name='landscaperprofilies',
            old_name='service_reminder_enabled',
            new_name='job_reminder',
        ),
    ]
