# Generated by Django 4.2.10 on 2026-03-02 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0014_remove_landscaperprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_rename_calendar_sync_enabled_clientprofile_calendar_sync_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandscaperProfile',
            new_name='BusinessProfile',
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='pro_landscaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landscapers.businessprofile'),
        ),
    ]
