# Generated by Django 4.2.10 on 2026-03-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_landscaperprofile_businessprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
    ]
