# Generated by Django 5.2.8 on 2026-01-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_landscaperprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
