# Generated by Django 4.2.10 on 2026-03-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0032_clientcustomservice_booking'),
        ('profiles', '0009_delete_businessprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landscaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_clients', to='landscapers.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='externalclient',
            constraint=models.UniqueConstraint(fields=('landscaper', 'email', 'phone'), name='unique_external_client_per_landscaper_email_phone'),
        ),
    ]
