# Generated by Django 5.2.8 on 2026-01-14 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_workerprofile_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='pro_landscaper',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='landscaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.landscaperprofile'),
        ),
    ]
