# Generated by Django 5.2.8 on 2026-01-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0007_remove_landscaperprofile_service_address'),
        ('profiles', '0011_remove_workerprofile_pro_landscaper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='landscaper',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='pro_landscaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landscapers.landscaperprofile'),
        ),
    ]
