# Generated by Django 5.2.8 on 2026-01-24 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_workerprofile_landscaper_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandscaperProfile',
            new_name='LandscaperProfilies',
        ),
    ]
