# Generated by Django 5.2.8 on 2026-02-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_rename_landscaperprofile_landscaperprofilies'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscaperprofilies',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=10),
        ),
    ]
