# Generated by Django 4.2.10 on 2026-03-13 20:49

import cloudinary.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingrequest_is_active'),
        ('profiles', '0008_rename_landscaperprofile_businessprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
        ('landscapers', '0032_clientcustomservice_booking'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=10)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('standard_service', 'Standard Service'), ('addon', 'Addon'), ('custom', 'Custom')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_date', models.DateField()),
                ('old_time', models.TimeField()),
                ('new_date', models.DateField()),
                ('new_time', models.TimeField()),
                ('reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='date',
            new_name='scheduled_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='end_time',
            new_name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='job',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='job',
            name='images',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_reduced',
        ),
        migrations.RemoveField(
            model_name='job',
            name='property',
        ),
        migrations.RemoveField(
            model_name='job',
            name='start_time',
        ),
        migrations.AddField(
            model_name='job',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='bookings.bookingrequest'),
        ),
        migrations.AddField(
            model_name='job',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='property.property'),
        ),
        migrations.AddField(
            model_name='job',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='profiles.clientprofile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='landscaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='landscapers.businessprofile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['client'], name='jobs_job_client__f1de35_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['landscaper'], name='jobs_job_landsca_a60417_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['scheduled_date'], name='jobs_job_schedul_d37e80_idx'),
        ),
        migrations.AddField(
            model_name='jobreschedule',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobreschedule',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reschedule_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_items', to='landscapers.addon'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_job_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_items', to='landscapers.service'),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
