# Generated by Django 4.2.10 on 2026-03-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobimage_jobitem_jobreschedule_alter_job_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_client__f1de35_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_landsca_a60417_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_status_7d017a_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_schedul_d37e80_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
