# Generated by Django 4.2.10 on 2026-03-17 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingrequestitem'),
        ('profiles', '0010_externalclient_and_more'),
        ('jobs', '0003_remove_job_jobs_job_client__f1de35_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='external_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='profiles.externalclient'),
        ),
        migrations.AlterField(
            model_name='job',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='bookings.bookingrequest'),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='profiles.clientprofile'),
        ),
    ]
