# Generated by Django 4.2.10 on 2026-04-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_external_client_alter_job_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='upcoming', max_length=20),
        ),
    ]
