# Generated by Django 4.2.10 on 2026-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_payment_status_alter_job_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
