# Generated by Django 4.2.10 on 2026-06-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobreschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
