# Generated by Django 4.2.10 on 2026-06-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobitem_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobitem',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='reminder_sent_at',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
