# Generated by Django 4.2.10 on 2026-02-04 00:59

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandscaperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pro_landscaper')),
                ('business_name', models.CharField(max_length=150)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landscaper_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_services', models.JSONField(blank=True, default=list)),
                ('custom_service', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('add_ons', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_square_feet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landscaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('landscaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='landscapers.landscaperprofile')),
            ],
            options={
                'unique_together': {('landscaper', 'day')},
            },
        ),
    ]
