# Generated by Django 4.2.10 on 2026-02-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscaperprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
        migrations.AlterField(
            model_name='landscaperprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
    ]
