# Generated by Django 5.2.8 on 2025-12-24 00:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscaperprofile',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pro_landscaper'),
        ),
    ]
