# Generated by Django 4.2.10 on 2026-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0002_alter_landscaperprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='latitude',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='longitude',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
    ]
