# Generated by Django 4.2.10 on 2026-02-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0003_alter_service_latitude_alter_service_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscaperprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='landscaperprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
    ]
