# Generated by Django 5.2.8 on 2026-01-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0003_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='landscaperprofile',
            name='add_ons',
            field=models.JSONField(blank=True, default=list, help_text='Optional add-on services'),
        ),
        migrations.AddField(
            model_name='landscaperprofile',
            name='standard_services',
            field=models.JSONField(blank=True, default=list, help_text='List of standard services selected by landscaper'),
        ),
    ]
