# Generated by Django 5.2.8 on 2026-01-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0004_landscaperprofile_add_ons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscaperprofile',
            name='add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='landscaperprofile',
            name='standard_services',
            field=models.JSONField(default=list),
        ),
    ]
