# Generated by Django 4.2.10 on 2026-02-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0004_alter_landscaperprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True),
        ),
    ]
