# Generated by Django 5.2.8 on 2026-01-11 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0005_alter_landscaperprofile_add_ons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landscaperprofile',
            name='add_ons',
        ),
        migrations.RemoveField(
            model_name='landscaperprofile',
            name='standard_services',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_services', models.JSONField(blank=True, default=list)),
                ('custom_service', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('add_ons', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_square_feet', models.DecimalField(decimal_places=2, default=0, help_text='Price per square foot', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landscaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
