# Generated by Django 4.2.10 on 2026-02-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0005_alter_service_latitude_alter_service_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='add_ons',
        ),
        migrations.RemoveField(
            model_name='service',
            name='custom_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='per_square_feet',
        ),
        migrations.RemoveField(
            model_name='service',
            name='standard_services',
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='rate_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('hourly', 'Hourly')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='standard_service',
            field=models.CharField(blank=True, choices=[('lawn_mowing', 'Lawn Mowing'), ('garden_design', 'Garden Design'), ('tree_trimming', 'Tree Trimming'), ('fertilization', 'Fertilization'), ('irrigation', 'Irrigation')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
