# Generated by Django 5.2.8 on 2026-01-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0006_remove_landscaperprofile_add_ons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landscaperprofile',
            name='service_address',
        ),
    ]
