# Generated by Django 4.2.10 on 2026-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0006_remove_service_add_ons_remove_service_custom_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='standard_service',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
