# Generated by Django 5.2.8 on 2026-01-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0007_remove_landscaperprofile_service_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landscaperprofile',
            old_name='profile',
            new_name='profile_image',
        ),
        migrations.AlterField(
            model_name='service',
            name='per_square_feet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
