# Generated by Django 4.2.10 on 2026-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0007_alter_service_standard_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Duration in hours (calculated from input minutes)', max_digits=5),
        ),
    ]
