# Generated by Django 4.2.10 on 2026-02-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0008_alter_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('hourly', 'Hourly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=5),
        ),
    ]
