# Generated by Django 4.2.10 on 2026-02-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0009_alter_service_price_alter_service_rate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
