# Generated by Django 4.2.10 on 2026-03-02 22:00

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landscapers', '0010_service_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('tagline', models.CharField(blank=True, help_text='Short description or tagline about the business', max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=18, max_digits=20, null=True)),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pro_landscaper')),
                ('quickbooks_connected', models.BooleanField(default=False)),
                ('insurance_doc', cloudinary.models.CloudinaryField(blank=True, help_text='Upload business insurance document if required', max_length=255, null=True, verbose_name='insurance_doc')),
                ('license_doc', cloudinary.models.CloudinaryField(blank=True, help_text='Upload business license document if required', max_length=255, null=True, verbose_name='license_doc')),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='landscaper',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='rate_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='standard_service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='time',
        ),
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('request', 'Priced Upon Request')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='landscapers.businessprofile'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['business', 'is_active'], name='landscapers_busines_c3d409_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['pricing_type'], name='landscapers_pricing_4d9e38_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_pinned'], name='landscapers_is_pinn_68dbfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_service_per_business'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
