# Generated by Django 4.2.10 on 2026-03-02 22:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_calendar_sync_enabled_clientprofile_calendar_sync_and_more'),
        ('landscapers', '0011_businessprofile_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Custom service name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Service description', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of delete')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_services', to='profiles.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client'], name='landscapers_client__7787d3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clientcustomservice',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='unique_custom_service_per_client'),
        ),
    ]
