# Generated by Django 4.2.10 on 2026-03-02 22:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_calendar_sync_enabled_clientprofile_calendar_sync_and_more'),
        ('landscapers', '0012_clientcustomservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add-On নাম', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='অতিরিক্ত মূল্য', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('applicable_service_ids', models.JSONField(blank=True, default=list, help_text='Applicable service IDs')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='profiles.landscaperprofilies')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['business'], name='landscapers_busines_b8ec67_idx'), models.Index(fields=['name'], name='landscapers_name_65c35d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='addon',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_addon_per_business'),
        ),
    ]
