# Generated by Django 4.2.10 on 2026-03-02 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0013_addon_addon_unique_addon_per_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landscaperprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='landscaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='landscapers.businessprofile'),
        ),
    ]
