# Generated by Django 4.2.10 on 2026-03-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_alter_landscaperqrcode_landscaper'),
        ('invitations', '0002_alter_teaminvitation_landscaper'),
        ('landscapers', '0014_remove_landscaperprofile_user_and_more'),
        ('profiles', '0008_rename_landscaperprofile_businessprofile_and_more'),
        ('bookings', '0002_alter_servicebooking_landscaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandscaperProfile',
        ),
    ]
