# Generated by Django 4.2.10 on 2026-03-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0015_delete_landscaperprofile'),
    ]

    operations = [
    ]
