# # Generated by Django 4.2.10 on 2026-03-03 20:39

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('landscapers', '0016_auto_20260303_2036'),
#     ]

#     operations = [
#     ]
# landscapers/migrations/0017_add_name_to_service.py
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0016_auto_20260303_2036'),  # keep your last migration
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150, default='Unnamed Service'),
            preserve_default=False,
        ),
    ]