# Generated by Django 4.2.10 on 2026-03-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0017_auto_20260303_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomservice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', help_text='Track landscaper response to the service', max_length=10),
        ),
        migrations.AddIndex(
            model_name='clientcustomservice',
            index=models.Index(fields=['status'], name='landscapers_status_0c7074_idx'),
        ),
    ]
