# Generated by Django 4.2.10 on 2026-03-03 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0018_clientcustomservice_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='addon',
            name='landscapers_busines_b8ec67_idx',
        ),
        migrations.RemoveIndex(
            model_name='addon',
            name='landscapers_name_65c35d_idx',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='applicable_service_ids',
        ),
        migrations.AddField(
            model_name='addon',
            name='applicable_services',
            field=models.ManyToManyField(blank=True, related_name='addons', to='landscapers.service'),
        ),
        migrations.AddField(
            model_name='addon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
