# Generated by Django 4.2.10 on 2026-03-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0021_alter_businessprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomservice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', help_text='Track landscaper response to the service', max_length=10),
        ),
    ]
