# Generated by Django 4.2.10 on 2026-03-04 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0022_alter_clientcustomservice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
