# Generated by Django 4.2.10 on 2026-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0023_alter_clientcustomservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomservice',
            name='note',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
