# Generated by Django 4.2.10 on 2026-03-10 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0024_clientcustomservice_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['day', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workinghours',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='workinghours',
            index=models.Index(fields=['landscaper', 'day'], name='landscapers_landsca_16078a_idx'),
        ),
    ]
