# Generated by Django 4.2.10 on 2026-03-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0025_alter_workinghours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='clientcustomservice',
            name='unique_custom_service_per_client',
        ),
        migrations.AddField(
            model_name='clientcustomservice',
            name='landscaper',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='received_custom_requests',
                to='landscapers.businessprofile',
            ),
        ),
        migrations.AlterField(
            model_name='clientcustomservice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='clientcustomservice',
            index=models.Index(fields=['landscaper'], name='landscapers_landsca_a15ac8_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientcustomservice',
            constraint=models.UniqueConstraint(fields=('client', 'landscaper', 'name'), name='unique_custom_service_per_landscaper'),
        ),
    ]
