# Generated by Django 4.2.10 on 2026-03-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0027_auto_20260311_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomservice',
            name='landscaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_custom_requests', to='landscapers.businessprofile'),
        ),
    ]
