# Generated by Django 4.2.10 on 2026-03-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0028_alter_clientcustomservice_landscaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomservice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', help_text='Track custom service flow', max_length=10),
        ),
    ]
