# Generated by Django 4.2.10 on 2026-03-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_landscaperprofile_businessprofile_and_more'),
        ('landscapers', '0029_alter_clientcustomservice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcustomservice',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='clientcustomservice',
            name='unique_custom_service_per_landscaper',
        ),
        migrations.RemoveIndex(
            model_name='clientcustomservice',
            name='landscapers_client__7787d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientcustomservice',
            name='landscapers_status_0c7074_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientcustomservice',
            name='landscapers_landsca_a15ac8_idx',
        ),
        migrations.AddField(
            model_name='clientcustomservice',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcustomservice',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientcustomservice',
            name='recurring_day_of_week',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientcustomservice',
            name='recurring_type',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly')], help_text='Set only for recurring services', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientcustomservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.clientprofile'),
        ),
        migrations.AlterField(
            model_name='clientcustomservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clientcustomservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientcustomservice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientcustomservice',
            name='landscaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscapers.businessprofile'),
        ),
        migrations.AlterField(
            model_name='clientcustomservice',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='clientcustomservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientcustomservice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
