# Generated by Django 4.2.10 on 2026-03-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('landscapers', '0030_alter_clientcustomservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomservice',
            name='property',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='custom_services', to='property.property'),
            preserve_default=False,
        ),
    ]
