# Generated by Django 4.2.10 on 2026-03-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingrequest_job_created'),
        ('landscapers', '0031_clientcustomservice_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomservice',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.bookingrequest'),
        ),
    ]
