# Generated by Django 4.2.10 on 2026-04-24 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0032_clientcustomservice_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomservice',
            name='landscaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landscapers.businessprofile'),
        ),
    ]
