# Generated by Django 4.2.10 on 2026-04-28 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        ('profiles', '0010_externalclient_and_more'),
        ('landscapers', '0033_alter_clientcustomservice_landscaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('counter_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('converted', 'Converted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_quotes', to='profiles.clientprofile')),
                ('landscaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_quotes', to='landscapers.businessprofile')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='landscapers.service')),
            ],
        ),
    ]
