# Generated by Django 4.2.10 on 2026-05-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0034_servicequote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='service',
            name='longitude',
        ),
    ]
