# Generated by Django 4.2.10 on 2026-05-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0035_remove_service_latitude_remove_service_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicequote',
            old_name='counter_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='servicequote',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='servicequote',
            name='requested_price',
        ),
        migrations.AddField(
            model_name='servicequote',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicequote',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
