# Generated by Django 4.2.10 on 2026-06-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0036_rename_counter_price_servicequote_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='service_radius_km',
            field=models.PositiveIntegerField(default=20, help_text='How far the landscaper is willing to travel'),
        ),
    ]
