# Generated by Django 4.2.10 on 2026-07-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0037_businessprofile_service_radius_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
