# Generated by Django 4.2.10 on 2026-07-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0038_alter_businessprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
    ]
