# Generated by Django 5.2.8 on 2025-12-24 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landscapers', '0002_landscaperprofile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('landscaping', 'Landscaping'), ('lawn_care', 'Lawn Care'), ('tree_trimming', 'Tree Trimming'), ('irrigation', 'Irrigation'), ('garden_design', 'Garden Design'), ('paving', 'Paving'), ('fence_installation', 'Fence Installation'), ('other', 'Other')], max_length=50)),
                ('is_addon', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Only Pro landscapers can set this', max_digits=10, null=True)),
                ('square_feet', models.DecimalField(blank=True, decimal_places=2, help_text='Only Pro landscapers can set this', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landscaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='landscapers.landscaperprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('landscaper', 'name')},
            },
        ),
    ]
