# Generated by Django 5.2.8 on 2026-01-07 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_workerprofile_image_clientprofile'),
        ('services', '0002_remove_service_is_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientServicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_preferences', to='profiles.clientprofile')),
                ('services', models.ManyToManyField(blank=True, related_name='selected_by_clients', to='services.service')),
            ],
        ),
    ]
