# Generated by Django 4.2.10 on 2026-02-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_clientservice_landscaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceschedule',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cash_pending', 'Cash Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
