# Generated by Django 5.2.8 on 2026-01-17 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_workerprofile_landscaper_and_more'),
        ('services', '0003_clientservicepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservicepreference',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_preferences', to='profiles.clientprofile'),
        ),
    ]
