# Generated by Django 4.2.10 on 2026-02-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceschedule_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceschedule',
            name='completion_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
