# Generated by Django 5.2.8 on 2026-02-10 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_landscaperprofilies_user_landscaperprofile'),
        ('services', '0004_serviceschedule_completion_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='landscaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.landscaperprofilies'),
        ),
    ]
