# Generated by Django 5.2.8 on 2026-01-18 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0007_remove_landscaperprofile_service_address'),
        ('services', '0004_alter_clientservicepreference_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='landscaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='landscapers.landscaperprofile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='square_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
