# Generated by Django 4.2.10 on 2026-02-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceschedule_completion_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceschedule',
            name='completed_services',
            field=models.ManyToManyField(blank=True, related_name='completed_jobs', to='services.clientservice'),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
