# Generated by Django 5.2.8 on 2026-01-21 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_workerprofile_landscaper_and_more'),
        ('services', '0005_service_is_standard_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservicepreference',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_preference', to='profiles.clientprofile'),
        ),
    ]
