# Generated by Django 4.2.10 on 2026-02-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceschedule_completed_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceschedule',
            name='price',
        ),
    ]
