# Generated by Django 4.2.10 on 2026-02-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_serviceschedule_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecompletionimage',
            name='image_type',
            field=models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='after', max_length=10),
        ),
    ]
