# Generated by Django 5.2.8 on 2026-01-29 17:48

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0008_rename_profile_landscaperprofile_profile_image_and_more'),
        ('profiles', '0013_rename_landscaperprofile_landscaperprofilies'),
        ('services', '0007_service_image_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservicepreference',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='service-image'),
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.clientprofile')),
                ('landscaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscapers.landscaperprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleCompletionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='completed-work')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.serviceschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
