# Generated by Django 4.2.10 on 2026-02-23 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_addonservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonservice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_on_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addonservice',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='addonservice',
            unique_together={('client', 'name')},
        ),
    ]
