# Generated by Django 5.2.8 on 2026-01-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_clientservicepreference_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceschedule',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
