# Generated by Django 4.2.10 on 2026-02-23 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0009_addonservice_client_alter_addonservice_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonservice',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add_on_services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
