# Generated by Django 5.2.8 on 2026-01-30 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0008_rename_profile_landscaperprofile_profile_image_and_more'),
        ('services', '0009_alter_serviceschedule_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceschedule',
            name='landscaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landscapers.landscaperprofile'),
        ),
    ]
