# Generated by Django 4.2.10 on 2026-04-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_addonservice_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulecompletionimage',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='serviceschedule',
            name='client',
        ),
        migrations.RemoveField(
            model_name='serviceschedule',
            name='completed_services',
        ),
        migrations.RemoveField(
            model_name='serviceschedule',
            name='landscaper',
        ),
        migrations.RemoveField(
            model_name='serviceschedule',
            name='service',
        ),
        migrations.DeleteModel(
            name='AddOnService',
        ),
        migrations.DeleteModel(
            name='ScheduleCompletionImage',
        ),
        migrations.DeleteModel(
            name='ServiceSchedule',
        ),
    ]
