# Generated by Django 5.2.8 on 2025-12-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('landscaper', 'Landscaper'), ('worker', 'Worker')], max_length=20),
        ),
    ]
