# Generated by Django 4.2.10 on 2026-03-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sitevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteVisit',
        ),
    ]
