# Generated by Django 4.2.10 on 2026-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_notification',
            field=models.BooleanField(default=False),
        ),
    ]
