# Generated by Django 4.2.10 on 2026-05-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
