
"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 5.2.8
"""
# import notifications.firebase

import os
from pathlib import Path
from datetime import timedelta
import os
from decouple import config
from dotenv import load_dotenv
from pathlib import Path

# from subscriptions.middleware import SubscriptionMiddleware



BASE_DIR = Path(__file__).resolve().parent.parent
# ------------------------------------------------------------------------------
# LOAD ENV
# ------------------------------------------------------------------------------
load_dotenv()

# ------------------------------------------------------------------------------
# BASE DIR
# ------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------
# SECURITY
# ------------------------------------------------------------------------------
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-dev-key-change-in-production"
)

DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",

    default="localhost,127.0.0.1,api.yardlinkapp.com"
).split(",")

CSRF_TRUSTED_ORIGINS = [
    "https://api.yardlinkapp.com",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ------------------------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",

    # Third-party
    "rest_framework",
    "corsheaders",
    "cloudinary",
    "cloudinary_storage",
    "django_rq",
    "channels",
    "django_filters",

    # Local apps
    'common',
    "accounts",
    "profiles",
    "chat",
    "message",
    "subscriptions",
    "landscapers",
    "services",
    "weather",
    "property",
    "invitations",
    'qr',
    'bookings',
    'connections',
    'jobs',
    'reviews',
    'payments',
    'notifications.apps.NotificationsConfig',
    'overview',
    'reports',
    'invoice',
    'quickbooks',
    
]

# ------------------------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://localhost:3000,http://10.10.13.15:3000,https://b2c-kohl.vercel.app').split(',')

# ------------------------------------------------------------------------------
# URLS / TEMPLATES
# ------------------------------------------------------------------------------
ROOT_URLCONF = "core.urls"
# settings.py
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],   # add this
        "APP_DIRS": True,                   # keep this True
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]



WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"
# WSGI_APPLICATION = "core.wsgi.application"

MIDDLEWARE += ["subscriptions.middleware.SubscriptionMiddleware"]
# ------------------------------------------------------------------------------
# DATABASE
# ------------------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME", default="ayon"),
        "USER": config("DB_USER", default="postgres"),
        "PASSWORD": config("DB_PASSWORD", default="postgres"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}

# ------------------------------------------------------------------------------
# AUTH
# ------------------------------------------------------------------------------
AUTH_USER_MODEL = "accounts.User"

# FIREBASE_CREDENTIALS_PATH = BASE_DIR / "serviceAccountKey.json"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------------------------------------------------------------
# DJANGO REST FRAMEWORK + JWT
# ------------------------------------------------------------------------------
REST_FRAMEWORK = {
    # Authentication
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.TokenAuthentication',
    # ),

    # Default permission
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    # Pagination
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  

    # Filtering & search
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),

    # Optional: default ordering param
    "ORDERING_PARAM": "ordering",
}


# celery
# celery.py or settings.py
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'job-reminders': {
        'task': 'notifications.tasks.send_job_reminders',
        'schedule': crontab(minute='*/10'),  # every 10 minutes
    },
    'client-service-reminders': {
        'task': 'notifications.tasks.send_client_service_reminders',
        'schedule': crontab(minute='*/10'),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "UPDATE_LAST_LOGIN": True,
}

# ------------------------------------------------------------------------------
# CHANNELS + REDIS
# ------------------------------------------------------------------------------
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(
                config("REDIS_HOST", default="redis"),
                config("REDIS_PORT", default=6379, cast=int),
            )],
        },
    },
}

# Celery
# core/settings.py
# Celery
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL)

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Optional: periodic task settings
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"


RQ_QUEUES = {
    "default": {
        "URL": config("REDIS_URL", default="redis://redis:6379/1"),
        "DEFAULT_TIMEOUT": 360,
    }
}
BACKEND_BASE_URL = "https://api.yardlinkapp.com/"

# ------------------------------------------------------------------------------
# CLOUDINARY
# ------------------------------------------------------------------------------
import cloudinary
import cloudinary.uploader
import cloudinary.api

CLOUDINARY = {
    "cloud_name": config("CLOUDINARY_CLOUD_NAME"),
    "api_key": config("CLOUDINARY_API_KEY"),
    "api_secret": config("CLOUDINARY_API_SECRET"),
}

cloudinary.config(
    cloud_name=CLOUDINARY["cloud_name"],
    api_key=CLOUDINARY["api_key"],
    api_secret=CLOUDINARY["api_secret"],
)

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
MEDIA_URL = "/media/"

# ------------------------------------------------------------------------------
# STRIPE
# ------------------------------------------------------------------------------
from decouple import config

STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")
STRIPE_PUBLIC_KEY = config("STRIPE_PUBLIC_KEY")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET")
# STRIPE_PAYMENT_WEBHOOK_SECRET = config("STRIPE_PAYMENT_WEBHOOK_SECRET")
print("WEBHOOK SECRET:", STRIPE_WEBHOOK_SECRET)
# quickbooks

QUICKBOOKS_CLIENT_ID = os.getenv("QUICKBOOKS_CLIENT_ID")
QUICKBOOKS_CLIENT_SECRET = os.getenv("QUICKBOOKS_CLIENT_SECRET")
QUICKBOOKS_REDIRECT_URI = os.getenv("QUICKBOOKS_REDIRECT_URI")
QUICKBOOKS_REALM_ID = os.getenv("QUICKBOOKS_REALM_ID")
QUICKBOOKS_ENVIRONMENT = os.getenv("QUICKBOOKS_ENVIRONMENT", "sandbox")
QUICKBOOKS_MINOR_VERSION = os.getenv("QUICKBOOKS_MINOR_VERSION", "75")
QUICKBOOKS_TOKEN_ENCRYPTION_KEY = os.getenv("QUICKBOOKS_TOKEN_ENCRYPTION_KEY")


# ------------------------------------------------------------------------------
# EMAIL
# ------------------------------------------------------------------------------
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="YardLink <noreply@yardlink.com>"
)

# ------------------------------------------------------------------------------
# WEATHER
# ------------------------------------------------------------------------------
# WEATHER SETTINGS
WEATHER_API_KEY = "a8be0217636541c2b0b214446262001"  # <-- Paste your real WeatherAPI key here
DEFAULT_CITY = "Dhaka,BD"
RAIN_ALERT_THRESHOLD = 30


# ------------------------------------------------------------------------------
# COOKIES / SECURITY
# ------------------------------------------------------------------------------
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# ------------------------------------------------------------------------------
# I18N
# ------------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -----------------------------
# STATIC FILES
# -----------------------------
STATIC_URL = "/static/"  # URL for static files

# During development, optional global static folder
STATIC_ROOT = BASE_DIR / "staticfiles"

# Where collectstatic will collect all static files for production
STATIC_ROOT = BASE_DIR / "staticfiles"  

# -----------------------------
# MEDIA FILES (for uploads)
# -----------------------------
MEDIA_URL = "/media/"  # URL for media files
MEDIA_ROOT = BASE_DIR / "media"  # folder where uploaded files are stored


# ------------------------------------------------------------------------------
# DEFAULT PK
# ------------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
