# Generated by Django 4.2.10 on 2026-03-24 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0003_invoice_net_amount_invoice_service_fee_amount_and_more'),
        ('landscapers', '0032_clientcustomservice_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, max_length=100)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField()),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('landscaper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_connection', to='landscapers.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='QuickBooksSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('customer', 'Customer'), ('invoice', 'Invoice'), ('payment', 'Payment')], max_length=20)),
                ('object_id_in_qbo', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='quickbooks.quickbooksconnection')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_sync_logs', to='invoice.invoice')),
            ],
        ),
    ]
