# Generated by Django 4.2.10 on 2026-03-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksconnection',
            name='default_deposit_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksconnection',
            name='default_deposit_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksconnection',
            name='default_service_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksconnection',
            name='default_service_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
