# Generated by Django 4.2.10 on 2026-03-24 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0032_clientcustomservice_booking'),
        ('quickbooks', '0002_quickbooksconnection_default_deposit_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('landscaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_oauth_states', to='landscapers.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
