# Generated by Django 5.2.8 on 2025-12-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionPlan',
            new_name='Plan',
        ),
    ]
