# Generated by Django 5.2.8 on 2025-12-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_subscriptionplan_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
