# Generated by Django 4.2.10 on 2026-04-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptioninvoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionInvoice',
        ),
    ]
