# Generated by Django 4.2.10 on 2026-04-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_delete_subscriptioninvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('trialing', 'Trialing'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
