# Generated by Django 4.2.10 on 2026-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_day_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_notified_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
