# Generated by Django 4.2.10 on 2026-05-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_alter_teaminvitation_landscaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
