# Generated by Django 5.2.8 on 2026-01-06 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landscapers', '0003_workinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandscaperQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landscaper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='landscapers.landscaperprofile')),
            ],
        ),
    ]
