# Generated by Django 4.2.10 on 2026-02-13 19:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landscapers', '0003_alter_service_latitude_alter_service_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandscaperQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landscaper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='landscapers.landscaperprofile')),
            ],
        ),
    ]
