# Generated by Django 4.2.10 on 2026-03-02 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0014_remove_landscaperprofile_user_and_more'),
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landscaperqrcode',
            name='landscaper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='landscapers.businessprofile'),
        ),
    ]
