# Generated by Django 5.2.8 on 2026-01-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cash_pending', 'Cash Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
