# Generated by Django 4.2.10 on 2026-03-02 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0013_addon_addon_unique_addon_per_business'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='landscaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='landscapers.businessprofile'),
        ),
    ]
