# Generated by Django 4.2.10 on 2026-03-10 23:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_rename_landscaperprofile_businessprofile_and_more'),
        ('property', '0001_initial'),
        ('landscapers', '0026_alter_addon_options_and_more'),
        ('bookings', '0002_alter_servicebooking_landscaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('booking_type', models.CharField(choices=[('one_time', 'One-Time'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('custom', 'Custom')], default='one_time', max_length=10)),
                ('recurring_day_of_week', models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], help_text='Used for recurring bookings', max_length=10, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addons', models.ManyToManyField(blank=True, related_name='bookings', to='landscapers.addon')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='profiles.clientprofile')),
                ('landscaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='landscapers.businessprofile')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='property.property')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='landscapers.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client'], name='bookings_bo_client__b35f8b_idx'), models.Index(fields=['landscaper'], name='bookings_bo_landsca_adeb12_idx'), models.Index(fields=['status'], name='bookings_bo_status_d3a735_idx'), models.Index(fields=['scheduled_date'], name='bookings_bo_schedul_93eaff_idx')],
            },
        ),
    ]
