# Generated by Django 5.2.8 on 2026-01-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_servicebooking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
