# Generated by Django 5.2.8 on 2026-01-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_servicebooking_stripe_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
