# Generated by Django 4.2.10 on 2026-03-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='job_created',
            field=models.BooleanField(default=False),
        ),
    ]
