# Generated by Django 4.2.10 on 2026-03-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingrequest_job_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
