# Generated by Django 4.2.10 on 2026-03-15 18:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0032_clientcustomservice_booking'),
        ('bookings', '0005_bookingrequest_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('standard_service', 'Standard Service'), ('addon', 'Addon'), ('custom', 'Custom')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='landscapers.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.bookingrequest')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_items', to='landscapers.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
