# Generated by Django 4.2.10 on 2026-06-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingrequestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='booking_type',
            field=models.CharField(choices=[('one_time', 'One-Time'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='one_time', max_length=10),
        ),
    ]
