# Generated by Django 5.2.8 on 2026-01-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='property',
            name='grass_types',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PropertyPhoto',
        ),
    ]
