# Generated by Django 5.2.8 on 2026-01-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_images_alter_property_grass_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_size',
            field=models.TextField(help_text="Size of the property (e.g., '1 ac', '120 m²', '5000 ft²')"),
        ),
    ]
