# Generated by Django 4.2.10 on 2026-03-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stripe_checkout_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
