# Generated by Django 4.2.10 on 2026-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_net_amount_invoice_service_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quickbooks_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quickbooks_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quickbooks_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
