# Generated by Django 4.2.10 on 2026-04-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_quickbooks_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sent_to_email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
