# Generated by Django 4.2.10 on 2026-04-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
    ]
