# Generated by Django 4.2.10 on 2026-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job', 'Job'), ('payment', 'Payment'), ('weather', 'Weather'), ('signup', 'Signup'), ('invoice', 'Invoice'), ('subscription', 'Subscription'), ('support', 'Support'), ('system', 'System')], max_length=20),
        ),
    ]
